<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Support;

use Illuminate\Support\Facades\Storage;

/**
 * Product image derivatives: original at `products/{id}/{name}.{ext}`,
 * WebP versions at `products/{id}/{name}-{size}.webp` (generated by
 * ProcessProductImage). width/height stay null until processed.
 */
final class ImageUrls
{
    /** @return array{w300: string, w800: string, w1600: string}|null */
    public static function for(string $disk, string $path, ?int $width): ?array
    {
        if ($width === null) {
            return null;
        }
        $urls = [];
        foreach ([300, 800, 1600] as $size) {
            $urls['w'.$size] = self::url($disk, self::derivative($path, $size));
        }

        return $urls;
    }

    public static function derivative(string $path, int $size): string
    {
        $dir = pathinfo($path, PATHINFO_DIRNAME);
        $name = pathinfo($path, PATHINFO_FILENAME);

        return ($dir !== '.' && $dir !== '' ? $dir.'/' : '').$name.'-'.$size.'.webp';
    }

    public static function url(string $disk, ?string $path): ?string
    {
        if ($path === null || $path === '') {
            return null;
        }

        try {
            return Storage::disk($disk)->url($path);
        } catch (\Throwable) {
            return null;
        }
    }
}
