<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Models;

use Database\Factories\Catalog\ProductImageFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Product image (DATABASE.md §3.1.6). `path` is generated by the server;
 * position 0 = cover.
 *
 * @property int $id
 * @property int $product_id
 * @property int|null $variant_id
 * @property string $disk
 * @property string $path
 * @property int $position
 */
class ProductImage extends Model
{
    /** @use HasFactory<ProductImageFactory> */
    use HasFactory;

    protected $table = 'product_images';

    protected $fillable = ['product_id', 'variant_id', 'disk', 'path', 'alt', 'width_px', 'height_px', 'position'];

    protected function casts(): array
    {
        return [
            'width_px' => 'integer',
            'height_px' => 'integer',
            'position' => 'integer',
        ];
    }

    /** @return BelongsTo<Product, $this> */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /** @return BelongsTo<ProductVariant, $this> */
    public function variant(): BelongsTo
    {
        return $this->belongsTo(ProductVariant::class, 'variant_id');
    }

    protected static function newFactory(): ProductImageFactory
    {
        return ProductImageFactory::new();
    }
}
